[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FourVectors = "b122eb78-8380-428a-b8c8-584a022ae8b6"
InstructionalDecayTrees = "1d606af4-d0f8-4ff7-bc8d-eb3f657b7647"

[sources]
InstructionalDecayTrees = {path = ".."}

[compat]
Documenter = "1"
FourVectors = "0.3.4"
julia = "1.10"
